pigot_arm_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joints_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_rot_1
      - arm_rot_2
      - arm_rot_3
      - arm_rot_4
      - arm_rot_5
      - arm_rot_6
    # gains: 
    #   joint1: {p: 10, i: 0.0, d: 0.05, i_clamp: 1}
    #   joint2: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    #   joint3: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    #   joint4: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    #   joint5: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
    #   joint6: {p: 10, i: 0.0, d: 0.0, i_clamp: 1}
  gazebo_ros_control:
    pid_gains:
      arm_rot_1:   {p: 100, i: 0.01, d: 10.0}
      arm_rot_2:   {p: 100, i: 0.01, d: 10.0}
      arm_rot_3:   {p: 100, i: 0.01, d: 10.0}
      arm_rot_4:   {p: 100, i: 0.01, d: 10.0}
      arm_rot_5:   {p: 100, i: 0.01, d: 10.0}
      arm_rot_6:   {p: 100, i: 0.01, d: 10.0}
      # arm_rot_7:  {p: 100, i: 0.01, d: 10.0}
      # arm_rot_8:  {p: 100, i: 0.01, d: 10.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_rot_1: {trajectory: 0.01, goal: 0.01}
      arm_rot_2: {trajectory: 0.01, goal: 0.01}
      arm_rot_3: {trajectory: 0.01, goal: 0.01}
      arm_rot_4: {trajectory: 0.01, goal: 0.01}
      arm_rot_5: {trajectory: 0.01, goal: 0.01}
      arm_rot_6: {trajectory: 0.01, goal: 0.01}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

